<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Companies' => '',
  'Company' => '',
  'Create' => '',
  'CreateARemark' => 'Create a remark',
  'Email' => '',
  'Employee' => '',
  'Employees' => '',
  'EventDate' => '',
  'Industry' => '',
  'Name' => '',
  'NoRemarks' => '',
  'Remark' => '',
  'Remarks' => '',
  'Significance' => '',
  'Sum' => '',
  'Tag' => '',
  'Timesheets' => '',
  'Users' => '',
  'week' => '',
  'year' => '',
  'Created' => '',
  'OrderTotal' => 'Order total',
  'month' => '',
  'BankAccounts' => 'Bank accounts',
  'BusinessId' => 'Business Id',
  'Communication' => 'Data communications',
  'CompanyInfo' => 'Company info',
  'CostBenefitCalculation' => 'Cost-benefit calculation',
  'CostBenefitCalculations' => 'Cost-benefit calculations',
  'CreateDate' => 'Create date',
  'CreateTime' => 'Create time',
  'Expenses' => 'Expenses',
  'FacilityExpenses' => 'Facility expenses',
  'Health' => 'Health',
  'Id' => 'ID',
  'Loans' => 'Loans',
  'OrderState' => 'Order state',
  'OtherExpenses' => 'Other expensest',
  'Planned' => 'Planned',
  'PurchaseOrders' => 'Purchase orders',
  'Realized' => 'Realized',
  'SalariesAndSideExpenses' => 'Salaries and side expenses',
  'SaleOrders' => 'Sale orders',
  'TokenKey' => 'Token key',
  'TotalAmount' => 'Total amount',
  'Turnover' => 'Turnover',
);
