<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'TheERPSystem' => 'The ERP system',
  'TheBank' => 'The bank',
  'TheLearningEnvironment' => 'The Futurality learning environment',
  'WhatIsNext' => 'What\'s next?',
  'OtherExpenses' => 'Other expenses',
  'computer-assembly' => 'Computer assembly',
  'computer-retail' => 'Computer retail',
  'BankAccount' => 'Bank account',
  'BusinessId' => 'Business ID',
  'Communication' => 'Communication',
  'CostBenefitCalculation' => 'Cost-benefit calculation',
  'Create' => 'Create',
  'CreateCompany' => 'Create a company',
  'Description' => 'Kuvaus',
  'EachTokenKeyCanBeUsedOnlyOnce' => 'Each token key can be used only once',
  'Email' => 'Email',
  'Employees' => 'Employees',
  'ErrorWhileDecidingFormStep' => 'Error while deciding the form step',
  'Expenses' => 'Expenses',
  'FuturalityAccount' => 'Your Futurality account',
  'FuturalityLearningEnvironment' => 'Futurality learning environment',
  'HaveFun' => 'Have fun!',
  'Health' => 'Health',
  'ID' => 'ID',
  'Industry' => 'Industry',
  'Loans' => 'Loans',
  'LoginFrom' => 'Login from',
  'Monthly' => 'Monthly',
  'Name' => 'Name',
  'OpenERPAccount' => 'OpenERP account',
  'Other' => 'Other',
  'OtherExpenses' => 'Other expenses',
  'Password' => 'Password',
  'PleaseGiveATokenKey' => 'Please give a token key',
  'Profit' => 'Profit',
  'Rents' => 'Rents',
  'Salaries' => 'Salaries',
  'SelectIndustry' => 'Select industry',
  'SideExpenses' => 'Side expenses',
  'Tag' => 'Tag',
  'TokenKey' => 'Token Key',
  'ToolTipCommunication' => 'Company communications. Ex. phones, data connections. Does not include marketing costs.',
  'ToolTipExpenses' => 'The expenses from buying the stuff you need to get your end product made.',
  'ToolTipHealth' => 'Mandatory and voluntary employee health plan costs.',
  'ToolTipLoans' => 'Loan costs. Includes service costs, interest and instalments.',
  'ToolTipOther' => 'Other expenses that does not fit in any spesific field.',
  'ToolTipProfit' => 'The profit you will get after all the expenses. This should be positive if you plan to stay in the business.',
  'ToolTipRents' => 'Total rents. Includes office rent and possible warehouse rents.',
  'ToolTipSalaries' => 'Employee salaries without side expenses. This is usually one of the most significant expenses in the company.',
  'ToolTipSideExpenses' => 'Salary side expenses.',
  'ToolTipTurnover' => 'Your revenue. The incoming money, from ex. sales. Does not include loans.',
  'TooltipCompanyName' => 'The company name. Stand out - Be creative!',
  'TooltipEmail' => 'Company email. You will receive the account information here.',
  'TooltipEmployees' => 'How many employees work in your company.',
  'TooltipIndustry' => 'The main industry of your company. It will be used to give you guideline values for your cost-benefit calculation.',
  'Turnover' => 'Turnover',
  'UserId' => 'UserID',
  'Verify' => 'Verify',
  'WelcomeToFuturality' => 'Welcome to Futurality',
  'Yearly' => 'Yearly',
  'YouHaveCreatedACompanyInThe' => 'You have created a company in the',
  'YourBusinessIdIs' => 'Your business ID is',
  'YourCompanyNameIs' => 'Your company name is',
  'YourCompanyTagIs' => 'Your company tag is',
);
