<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'ToolTipCommunication' => 'Yrityksen yhteydet ulkomaailmaan. Sisältää puhelimet, internetin, yms. Ei sisällä markkinointikuluja',
  'ToolTipExpenses' => 'Hankkimiskustannukset. Tämä sisältää esim. lopputuotteen kokoonpanoa varten ostettavat osat.',
  'ToolTipHealth' => 'Pakolliset ja vapaaehtoiset sairasvakuutukset ja muut työntekijöiden terveydenhuoltoon suunnatut kulut.',
  'ToolTipLoans' => '',
  'ToolTipOther' => '',
  'ToolTipProfit' => '',
  'ToolTipRents' => '',
  'ToolTipSalaries' => '',
  'ToolTipSideExpenses' => '',
  'ToolTipTurnover' => 'Myyntituotot, eli yritykselle tuleva raha. Ei sisällä lainoja.',
  'TooltipEmployees' => 'Yrityksen työntekijöiden määrä.',
  'CreateCompany' => 'Luo yritys',
  'EachTokenKeyCanBeUsedOnlyOnce' => 'Jokaisen  perustamisavaimen voi käyttää vain kerran',
  'Email' => 'Sähköposti',
  'Employees' => 'Työntekijät',
  'ErrorWhileDecidingFormStep' => 'Virheellinen lomakkeen vaihe',
  'ID' => 'ID',
  'Industry' => 'Toimiala',
  'Name' => 'Nimi',
  'PleaseGiveATokenKey' => 'Ole hyvä, ja anna perustamisavain',
  'SelectIndustry' => 'Valitse toimiala',
  'Tag' => 'Tunnus',
  'TokenKey' => 'Perustamisavain',
  'TooltipCompanyName' => 'Yrityksen nimi. Erotu joukosta - Ole luova!',
  'TooltipEmail' => 'Yrityksen sähköpostiosoite. Saat tilisi tiedot tähän sähköpostiin.',
  'TooltipIndustry' => 'Yrityksen päätoimiala. Tämän perusteella annetaan ohjearvot liiketoimintasuunnitelmaa varten.',
  'Verify' => 'Tarkista',
);
