<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create' => 'Luo',
  'Communication' => 'Yhteydet',
  'CreateCompany' => 'Luo yritys',
  'EachTokenKeyCanBeUsedOnlyOnce' => 'Jokaisen  perustamisavaimen voi käyttää vain kerran',
  'Email' => 'Sähköposti',
  'Employees' => 'Työntekijät',
  'ErrorWhileDecidingFormStep' => 'Virheellinen lomakkeen vaihe',
  'Expenses' => 'Kulut',
  'Health' => 'Terveys',
  'ID' => 'ID',
  'Industry' => 'Toimiala',
  'Loans' => 'Lainat',
  'Monthly' => 'Kuukaudessa',
  'Name' => 'Nimi',
  'Other' => 'Muut',
  'PleaseGiveATokenKey' => 'Ole hyvä, ja anna perustamisavain',
  'Profit' => 'Tuotto',
  'Rents' => 'Vuokrat',
  'Salaries' => 'Palkat',
  'SelectIndustry' => 'Valitse toimiala',
  'SideExpenses' => 'Sivukulut',
  'Tag' => 'Tunnus',
  'TokenKey' => 'Perustamisavain',
  'ToolTipCommunication' => 'Yrityksen yhteydet ulkomaailmaan. Sisältää puhelimet, internetin, yms. Ei sisällä markkinointikuluja',
  'ToolTipExpenses' => 'Hankkimiskustannukset. Tämä sisältää esim. lopputuotteen kokoonpanoa varten ostettavat osat.',
  'ToolTipHealth' => 'Pakolliset ja vapaaehtoiset sairasvakuutukset ja muut työntekijöiden terveydenhuoltoon suunnatut kulut.',
  'ToolTipLoans' => 'Lainanhoitokulut. Sisältää koron, maksuerän ja mahdolliset palvelu- tai hoitomaksut.',
  'ToolTipOther' => 'Muut kulut, jotka eivät sovi muihin kenttiin.',
  'ToolTipProfit' => 'Yrityksen tulos, joka jää kaikkien kulujen jälkeen. Tämän olisi syytä olla positiivinen, mikäli yritys aikoo pysyä toiminnassa.',
  'ToolTipRents' => 'Vuokrakulut yhteensä. Tämä sisältää toimitilan vuokran, ja mahdollisten varastotilojen vuokran',
  'ToolTipSalaries' => 'Palkkakulut ilman sivukuluja. Tämä on usein yksi yrityksen suurimmista menoeristä.',
  'ToolTipSideExpenses' => 'Palkkojen sivukulut',
  'ToolTipTurnover' => 'Myyntituotot, eli yritykselle tuleva raha. Ei sisällä lainoja.',
  'TooltipCompanyName' => 'Yrityksen nimi. Erotu joukosta - Ole luova!',
  'TooltipEmail' => 'Yrityksen sähköpostiosoite. Saat tilisi tiedot tähän sähköpostiin.',
  'TooltipEmployees' => 'Yrityksen työntekijöiden määrä.',
  'TooltipIndustry' => 'Yrityksen päätoimiala. Tämän perusteella annetaan ohjearvot liiketoimintasuunnitelmaa varten.',
  'Turnover' => 'Liikevaihto',
  'Verify' => 'Tarkista',
  'Yearly' => 'Vuodessa',
);
