<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create' => 'Luo',
  'CreateARemark' => 'Luo huomio',
  'EventDate' => 'Tapahtumapäivä',
  'NoRemarks' => 'Ei huomioita',
  'Remark' => 'Huomio',
  'Significance' => 'Vaikutus',
  'Sum' => 'Summa',
  'Timesheets' => 'Tuntilomakkeet',
  'Created' => 'Luotu',
  'OrderTotal' => 'Kokonaissumma',
  'User' => 'Käyttäjä',
  'month' => 'kuukausi',
  'BankAccounts' => 'Pankkitilit',
  'BusinessId' => 'Y-tunnus',
  'Communication' => 'Tietoliikenneyhteydet',
  'Companies' => 'Yritykset',
  'Company' => 'Yritys',
  'CompanyInfo' => 'Yrityksen tiedot',
  'CostBenefitCalculation' => 'Kannattavuuslaskelma',
  'CostBenefitCalculations' => 'Kannattavuuslaskelmat',
  'CreateDate' => 'Luontipäivä',
  'CreateTime' => 'Luontiaika',
  'Email' => 'Sähköposti',
  'Employee' => 'Työntekijä',
  'Employees' => 'Työntekijät',
  'Expenses' => 'Materiaalikulut',
  'FacilityExpenses' => 'Toimitilakulut',
  'Health' => 'Terveyskulut',
  'Id' => 'ID',
  'Industry' => 'Toimiala',
  'Loans' => 'Lainat',
  'Name' => 'Nimi',
  'OrderState' => 'Tila',
  'OtherExpenses' => 'Muut kulut',
  'Planned' => 'Suunniteltu',
  'PurchaseOrders' => 'Ostotilaukset',
  'Realized' => 'Toteutunut',
  'Remarks' => 'Huomiot',
  'SalariesAndSideExpenses' => 'Palkat ja sivukulut',
  'SaleOrders' => 'Myyntitilaukset',
  'Tag' => 'Tunnus',
  'TokenKey' => 'Perustamisavain',
  'TotalAmount' => 'Kokonaissumma',
  'Turnover' => 'Liikevaihto',
  'Users' => 'Käyttäjät',
  'week' => 'viikko',
  'year' => 'vuosi',
);
